### ISSUE TITLE
If you have enabled the gamerule doimmediaterespawn it will be detectet as a cheat

### ISSUE THREAD

**Issue by textilkleber1** [n33d4n4m3/NoCheatMinus#13]

**Comment by n33d4n4m3** [comment]
Resolved with #7328add

**Comment by DEVTomatoCake** [comment]
![2021-05-16 08_04_50](https://user-images.githubusercontent.com/60300461/118387223-7d741b00-b61d-11eb-8e0a-868a98d5b930.png)
Still flags sometimes for SurvivalFly

**Comment by n33d4n4m3** [comment]
@DEVTomatoCake Thanks. Resolved with c983271ae5aa33a838538115cc2d6bcff1e3008a
