### ISSUE TITLE
Attacks by iron golems cause flags

### ISSUE THREAD

**Issue by DEVTomatoCake** [n33d4n4m3/NoCheatMinus#19]
![2021-05-16 08_01_11](https://user-images.githubusercontent.com/60300461/118387159-f8890180-b61c-11eb-8836-07a20b75a21c.png)

**Comment by n33d4n4m3** [comment]
Resolved with https://github.com/n33d4n4m3/NoCheatMinus/commit/0b803d4b6c0eb3d5923beb8021138a397212ae7d
