### ISSUE TITLE
Creative and spectator players are flagged for SurvivalFly.Distance and .OffgroundTicks

### ISSUE THREAD

**Issue by DEVTomatoCake** [n33d4n4m3/NoCheatMinus#30]
![Bild_2021-11-14_123434](https://user-images.githubusercontent.com/60300461/141679105-c6dcb310-20f6-4d0c-a7c0-7c819c731793.png)

**Comment by DEVTomatoCake** [comment]
For spectator, when flying fast up or down players are flagged for Movement.SurvivalFlyConstandClimbRate
![Bild_2021-11-14_123535](https://user-images.githubusercontent.com/60300461/141679136-10f7056f-ffb5-46d7-93f7-169e91072443.png)

**Comment by DEVTomatoCake** [comment]
Also affects levitation effect

**Comment by n33d4n4m3** [comment]
> Also affects levitation effect

But Distance does not flag players with levitation effect, right?

**Comment by DEVTomatoCake** [comment]
It does
![Uploading Bild_2021-11-14_132349.png…]()

**Comment by n33d4n4m3** [comment]
Resolved with https://github.com/n33d4n4m3/NoCheatMinus/commit/65e490002d57f628d2af59621c154ba39adeddb7
