### ISSUE TITLE
If you sprint diagnoly it cause a false positive

### ISSUE THREAD

**Issue by Timong-craft** [n33d4n4m3/NoCheatMinus#35]

**Comment by n33d4n4m3** [comment]
Thanks for your contribution. I couldn't reproduce this false positive unfortunately. What flags do you get in the chat?
@Timong-craft

**Comment by Timong-craft** [comment]
Sorry, I'm currently in vacation I can test it on saturday or sunday

**Comment by Timong-craft** [comment]
Here is a video of it (it was too big)
https://drive.google.com/file/d/1wPi5MZyPOsVj7Nqa6nngTaI0GAOvL9Gr/view?usp=sharing

**Comment by Timong-craft** [comment]
It's a shame, but I hope the anticheat is a success and that you enjoy it.
